// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMytZwwqxzmOryiiF7BWU3kxWYd0OehrI',
    appId: '1:1008969943526:web:719fa6f6ba03c24937ee27',
    messagingSenderId: '1008969943526',
    projectId: 'aasyou-ecom',
    authDomain: 'aasyou-ecom.firebaseapp.com',
    storageBucket: 'aasyou-ecom.firebasestorage.app',
    measurementId: 'G-W1TJPSMYQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlMOpkwZxo731Kp5awQUeFqLjBk3_RIeU',
    appId: '1:1008969943526:android:b590b671cb44405f37ee27',
    messagingSenderId: '1008969943526',
    projectId: 'aasyou-ecom',
    storageBucket: 'aasyou-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnrqmgpy6k2-wXI71-BSfEfQNw68-K3s',
    appId: '1:1008969943526:ios:6ff1592979eb502137ee27',
    messagingSenderId: '1008969943526',
    projectId: 'aasyou-ecom',
    storageBucket: 'aasyou-ecom.firebasestorage.app',
    androidClientId: '1008969943526-7nsl90dp7hggtmmkqf1joscdf0bp5g4v.apps.googleusercontent.com',
    iosClientId: '1008969943526-c0atcuhp1l0e6hhh9onnk44vmu7rgaec.apps.googleusercontent.com',
    iosBundleId: 'com.aasyou.user',
  );
}
